CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR UNIQUE                                  NOT NULL,
    email VARCHAR UNIQUE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR UNIQUE                                  NOT NULL
);

CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR,
    pinned BOOLEAN
);

create table locations
(
    id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION

);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    title              VARCHAR                                         NOT NULL,
    annotation         VARCHAR                                         NOT NULL,
    description        VARCHAR                                         NOT NULL,
    state              VARCHAR                                         NOT NULL,
    paid               BOOLEAN                                         NOT NULL,
    request_moderation BOOLEAN                                         NOT NULL,
    confirmed_requests BIGINT,
    participant_limit  BIGINT,
    created            TIMESTAMP WITHOUT TIME ZONE,
    published          TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    category_id        BIGINT REFERENCES categories (id),
    initiator_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    location_id        BIGINT REFERENCES locations (id)
);

CREATE TABLE compilation_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE
);

CREATE TABLE requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR,
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE
);